### ISSUE TITLE
ContentDM loading breaks if rel_home is set to anything other than 'native'

### ISSUE THREAD

**Issue by adrq** [DigitalUSSouth/NativeAmericanSCArchive#8]
When I set the rel_home value in configuration to anything other than 'native' contentdm images on home page will not load. Clicking on an image gives "Error Code: -3".
I get the error when I set rel_home to '/nasca'
This is my configuration.xml
~~~~<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <rel_home>/nasca</rel_home>
  <databases>
    <cdm>
      <server>xxx.xxx</server>
      <port>81</port>
      <api_query_base>/dmwebservices/index.php?q=</api_query_base>
      <api_utils>/utils/ajaxhelper/?</api_utils>
      <collection>/nasca</collection>
    </cdm>
    <youtube>
    </youtube>
  </databases>
  <frontend>
    <home>
      <card_count>8</card_count>
    </home>
  </frontend>
  <backend>
  </backend>
</configuration>
~~~~
@Jendrasi do you know why it only works with '/native'?
![screen shot 2017-09-01 at 16 36 29](https://user-images.githubusercontent.com/13006456/29986943-bc41240a-8f33-11e7-8303-0cf8872a4a9e.png)

**Comment by adrq** [comment]
Fixed. It was an issue with my server config

**Comment by Jendrasi** [comment]
If on your personal computer and local server (localhost), you have kept the home of the site at localhost/native, then rel_home should be /native. If it is localhost/nasca, rel_home should be /nasca. It is just offering a handy variable to php and javascript to where the home of the site is relative to the public root of the server. On nativesouthcarolina.org, rel_home should be empty because nativesouthcarolina.org is the home of the site AND the root.

**Comment by adrq** [comment]
Yeah, thanks. I just a bad symlink in my apache config!
